# Generated by Django 3.2.13 on 2022-05-09 06:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lessor_profile', serialize=False, to='users.basiccustomer')),
            ],
            options={
                'verbose_name': 'Профиль арендодателя',
                'verbose_name_plural': 'Профили арендодателей',
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_profile', serialize=False, to='users.basiccustomer')),
            ],
            options={
                'verbose_name': 'Профиль арендатора',
                'verbose_name_plural': 'Профили арендаторов',
            },
        ),
        migrations.RemoveField(
            model_name='basiccustomer',
            name='role',
        ),
        migrations.AddField(
            model_name='basiccustomer',
            name='is_lessor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basiccustomer',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basiccustomer',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'incorrect': 'Incorrect mobile number.'}, max_length=128, region=None, verbose_name='mobile number'),
        ),
    ]
