# Generated by Django 3.2.13 on 2022-05-06 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malls', '0003_auto_20220506_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], null=True, verbose_name='кол-во звезд')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Оцениваемый пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'оценка пользователя',
                'verbose_name_plural': 'оценки пользователей',
            },
        ),
        migrations.CreateModel(
            name='MallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], null=True, verbose_name='кол-во звезд')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='malls.mall', verbose_name='тц')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_rating', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'оценка тц',
                'verbose_name_plural': 'оценки тц',
            },
        ),
        migrations.CreateModel(
            name='AreaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], null=True, verbose_name='кол-во звезд')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='malls.area', verbose_name='площадь для аренды')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_rating', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'оценка площади',
                'verbose_name_plural': 'оценки площадей',
            },
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user', 'evaluated_user'), name='user_rating_unique'),
        ),
        migrations.AddConstraint(
            model_name='mallrating',
            constraint=models.UniqueConstraint(fields=('user', 'mall'), name='mall_rating_unique'),
        ),
        migrations.AddConstraint(
            model_name='arearating',
            constraint=models.UniqueConstraint(fields=('user', 'area'), name='area_rating_unique'),
        ),
    ]
