# Generated by Django 3.2.13 on 2022-05-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ТЦ, максимум 50 символов', max_length=50, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание ТЦ', verbose_name='Описание')),
                ('address', models.CharField(help_text='Адрес ТЦ, максимум 150 символов', max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Торговый центр',
                'verbose_name_plural': 'Торговые центры',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Изображения ТЦ')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='malls.mall')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
