# Generated by Django 3.2.13 on 2022-05-25 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(help_text='Арендатор площади', on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
        migrations.AddField(
            model_name='mall',
            name='owner',
            field=models.ForeignKey(help_text='Владелец ТЦ', on_delete=django.db.models.deletion.CASCADE, related_name='malls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='malls.mall', verbose_name='Торговый центр'),
        ),
        migrations.AddField(
            model_name='area',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='malls.mall', verbose_name='Торговый центр'),
        ),
    ]
