# Generated by Django 3.2.13 on 2022-05-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='owner',
            field=models.ForeignKey(default=None, help_text='Владелец ТЦ', on_delete=django.db.models.deletion.CASCADE, related_name='malls', to='auth.user', verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='malls.mall', verbose_name='Торговый центр'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('available', models.BooleanField(choices=[(True, 'Свободно'), (False, 'Занято')], default=True, verbose_name='Доступность')),
                ('square', models.PositiveIntegerField(verbose_name='Площадь в кв. метрах')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas', to='malls.mall', verbose_name='Торговый центр')),
            ],
            options={
                'verbose_name': 'Площадь',
                'verbose_name_plural': 'Площади',
            },
        ),
    ]
