# Generated by Django 3.2.13 on 2022-05-06 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malls', '0002_auto_20220505_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='owner',
            field=models.ForeignKey(help_text='Владелец ТЦ', on_delete=django.db.models.deletion.CASCADE, related_name='malls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала аренды')),
                ('balance', models.BigIntegerField(verbose_name='Баланс')),
                ('status', models.BooleanField(choices=[(True, 'Активна'), (False, 'Закончилась')], default=True, verbose_name='Статус аренды')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents', to='malls.area', verbose_name='Площадь')),
                ('tenant', models.ForeignKey(help_text='Арендатор площади', on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
